/// Firestore Content Seeder
///
/// Run this once to populate Firestore with initial Tugen content.
/// Usage: dart run tools/seed_firestore.dart
///
/// You'll need to have Firebase CLI configured and a service account key.
/// Alternatively, use the Firebase console to import the JSON below.

import 'dart:convert';

/// Sample seed data — export as JSON and import via Firebase Console
/// or use the Admin SDK in a Node.js script.
final seedData = {
  'categories': [
    {
      'id': 'greetings',
      'nameEn': 'Greetings',
      'nameSw': 'Salamu',
      'nameTug': 'Chamgei',
      'icon': '👋',
      'sortOrder': 1,
    },
    {
      'id': 'numbers',
      'nameEn': 'Numbers',
      'nameSw': 'Nambari',
      'nameTug': 'Sigindeek',
      'icon': '🔢',
      'sortOrder': 2,
    },
    {
      'id': 'family',
      'nameEn': 'Family',
      'nameSw': 'Familia',
      'nameTug': 'Kapchi',
      'icon': '👨‍👩‍👧‍👦',
      'sortOrder': 3,
    },
    {
      'id': 'food',
      'nameEn': 'Food & Market',
      'nameSw': 'Chakula na Soko',
      'nameTug': 'Amageek ak Duka',
      'icon': '🍲',
      'sortOrder': 4,
    },
    {
      'id': 'travel',
      'nameEn': 'Travel & Directions',
      'nameSw': 'Safari na Maelekezo',
      'nameTug': 'Barak',
      'icon': '🗺️',
      'sortOrder': 5,
    },
    {
      'id': 'body',
      'nameEn': 'Body & Health',
      'nameSw': 'Mwili na Afya',
      'nameTug': 'Borto',
      'icon': '🏥',
      'sortOrder': 6,
    },
    {
      'id': 'nature',
      'nameEn': 'Nature & Animals',
      'nameSw': 'Mazingira na Wanyama',
      'nameTug': 'Ng\'ung\'unyeek',
      'icon': '🌿',
      'sortOrder': 7,
    },
    {
      'id': 'daily',
      'nameEn': 'Daily Life',
      'nameSw': 'Maisha ya Kila Siku',
      'nameTug': 'Sobondab betusieek',
      'icon': '☀️',
      'sortOrder': 8,
    },
  ],
  'phrases': [
    // Greetings
    {
      'id': 'g001',
      'categoryId': 'greetings',
      'tugen': 'Chamgei',
      'english': 'Hello / Welcome',
      'swahili': 'Habari / Karibu',
      'pronunciation': 'chahm-GAY',
      'difficulty': 1,
      'notes': 'Universal greeting, used at any time of day.',
    },
    {
      'id': 'g002',
      'categoryId': 'greetings',
      'tugen': 'Chamgei anan?',
      'english': 'How are you?',
      'swahili': 'Habari yako?',
      'pronunciation': 'chahm-GAY ah-NAHN',
      'difficulty': 1,
    },
    {
      'id': 'g003',
      'categoryId': 'greetings',
      'tugen': 'Amache',
      'english': 'I am fine / It is well',
      'swahili': 'Niko sawa',
      'pronunciation': 'ah-MAH-cheh',
      'difficulty': 1,
    },
    {
      'id': 'g004',
      'categoryId': 'greetings',
      'tugen': 'Kong\'oi',
      'english': 'Thank you',
      'swahili': 'Asante',
      'pronunciation': 'kong-OY',
      'difficulty': 1,
    },
    {
      'id': 'g005',
      'categoryId': 'greetings',
      'tugen': 'Kong\'oi missing',
      'english': 'Thank you very much',
      'swahili': 'Asante sana',
      'pronunciation': 'kong-OY mih-SING',
      'difficulty': 1,
    },
    {
      'id': 'g006',
      'categoryId': 'greetings',
      'tugen': 'Sait',
      'english': 'Goodbye',
      'swahili': 'Kwaheri',
      'pronunciation': 'sah-EET',
      'difficulty': 1,
    },
    {
      'id': 'g007',
      'categoryId': 'greetings',
      'tugen': 'Ee',
      'english': 'Yes',
      'swahili': 'Ndiyo',
      'pronunciation': 'eh',
      'difficulty': 1,
    },
    {
      'id': 'g008',
      'categoryId': 'greetings',
      'tugen': 'Achicha',
      'english': 'No',
      'swahili': 'Hapana',
      'pronunciation': 'ah-CHEE-chah',
      'difficulty': 1,
    },

    // Numbers
    {
      'id': 'n001',
      'categoryId': 'numbers',
      'tugen': 'Agenge',
      'english': 'One',
      'swahili': 'Moja',
      'pronunciation': 'ah-GENG-eh',
      'difficulty': 1,
    },
    {
      'id': 'n002',
      'categoryId': 'numbers',
      'tugen': 'Aeng\'',
      'english': 'Two',
      'swahili': 'Mbili',
      'pronunciation': 'ah-ENG',
      'difficulty': 1,
    },
    {
      'id': 'n003',
      'categoryId': 'numbers',
      'tugen': 'Somok',
      'english': 'Three',
      'swahili': 'Tatu',
      'pronunciation': 'SOH-mok',
      'difficulty': 1,
    },
    {
      'id': 'n004',
      'categoryId': 'numbers',
      'tugen': 'Ang\'wan',
      'english': 'Four',
      'swahili': 'Nne',
      'pronunciation': 'ANG-wahn',
      'difficulty': 1,
    },
    {
      'id': 'n005',
      'categoryId': 'numbers',
      'tugen': 'Mut',
      'english': 'Five',
      'swahili': 'Tano',
      'pronunciation': 'muht',
      'difficulty': 1,
    },
    {
      'id': 'n006',
      'categoryId': 'numbers',
      'tugen': 'Lo',
      'english': 'Six',
      'swahili': 'Sita',
      'pronunciation': 'loh',
      'difficulty': 2,
    },
    {
      'id': 'n007',
      'categoryId': 'numbers',
      'tugen': 'Tisap',
      'english': 'Seven',
      'swahili': 'Saba',
      'pronunciation': 'TEE-sahp',
      'difficulty': 2,
    },
    {
      'id': 'n008',
      'categoryId': 'numbers',
      'tugen': 'Sisit',
      'english': 'Eight',
      'swahili': 'Nane',
      'pronunciation': 'SEE-sit',
      'difficulty': 2,
    },
    {
      'id': 'n009',
      'categoryId': 'numbers',
      'tugen': 'Sogol',
      'english': 'Nine',
      'swahili': 'Tisa',
      'pronunciation': 'SOH-gol',
      'difficulty': 2,
    },
    {
      'id': 'n010',
      'categoryId': 'numbers',
      'tugen': 'Taman',
      'english': 'Ten',
      'swahili': 'Kumi',
      'pronunciation': 'TAH-mahn',
      'difficulty': 2,
    },

    // Family
    {
      'id': 'f001',
      'categoryId': 'family',
      'tugen': 'Papa',
      'english': 'Father',
      'swahili': 'Baba',
      'pronunciation': 'PAH-pah',
      'difficulty': 1,
    },
    {
      'id': 'f002',
      'categoryId': 'family',
      'tugen': 'Mama / Kamet',
      'english': 'Mother',
      'swahili': 'Mama',
      'pronunciation': 'kah-MET',
      'difficulty': 1,
    },
    {
      'id': 'f003',
      'categoryId': 'family',
      'tugen': 'Lakwa',
      'english': 'Child',
      'swahili': 'Mtoto',
      'pronunciation': 'LAHK-wah',
      'difficulty': 1,
    },
    {
      'id': 'f004',
      'categoryId': 'family',
      'tugen': 'Lagok',
      'english': 'Children',
      'swahili': 'Watoto',
      'pronunciation': 'LAH-gok',
      'difficulty': 1,
    },
    {
      'id': 'f005',
      'categoryId': 'family',
      'tugen': 'Kwanda',
      'english': 'Brother',
      'swahili': 'Kaka',
      'pronunciation': 'KWAHN-dah',
      'difficulty': 2,
    },
  ],
  'decks': [
    {
      'id': 'deck_greetings',
      'nameEn': 'Essential Greetings',
      'nameSw': 'Salamu Muhimu',
      'nameTug': 'Chamgeisiek',
      'description': 'Master the most common Tugen greetings and polite expressions.',
      'icon': '👋',
      'totalCards': 8,
      'isPremium': false,
    },
    {
      'id': 'deck_numbers',
      'nameEn': 'Numbers 1-10',
      'nameSw': 'Nambari 1-10',
      'nameTug': 'Sigindeek 1-10',
      'description': 'Learn to count in Tugen from one to ten.',
      'icon': '🔢',
      'totalCards': 10,
      'isPremium': false,
    },
    {
      'id': 'deck_family',
      'nameEn': 'Family Members',
      'nameSw': 'Wanafamilia',
      'nameTug': 'Kapchi',
      'description': 'Words for family relationships in Tugen.',
      'icon': '👨‍👩‍👧‍👦',
      'totalCards': 5,
      'isPremium': false,
    },
  ],
  'stories': [
    {
      'id': 'story_001',
      'titleEn': 'The Hare and the Hyena',
      'titleSw': 'Sungura na Fisi',
      'titleTug': 'Chebiit ak Kimnyigis',
      'description':
          'A classic Tugen folktale about cleverness and greed.',
      'durationSeconds': 300,
      'difficulty': 'beginner',
    },
    {
      'id': 'story_002',
      'titleEn': 'At the Market',
      'titleSw': 'Sokoni',
      'titleTug': 'Dukait',
      'description':
          'A dialogue between a buyer and seller at Kabarnet market.',
      'durationSeconds': 180,
      'difficulty': 'beginner',
    },
  ],
};

void main() {
  // Print as JSON for manual import to Firebase Console
  print(const JsonEncoder.withIndent('  ').convert(seedData));
  print('\n--- Copy the above JSON and import into Firestore ---');
  print('Or use firebase-admin SDK in Node.js to seed programmatically.');
}
